package POJOS;
// Generated 02-feb-2021 0:15:37 by Hibernate Tools 3.6.0


import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Edicion generated by hbm2java
 */
public class Edicion  implements java.io.Serializable {


     private EdicionId id;
     private Empregadofixo empregadofixo;
     private Date data;
     private String lugar;
     private Collection <Empregado> alumnos = new ArrayList();
     private Curso curso;

    public Edicion() {
    }

	
   
    public Edicion( Date data, String lugar, Empregadofixo empregadofixo) {
       this.data = data;
             
       this.lugar = lugar;
    this.empregadofixo = empregadofixo;
    }
   
    public EdicionId getId() {
        return this.id;
    }
    
    public void setId(EdicionId id) {
        this.id = id;
    }

    public Empregadofixo getEmpregadofixo() {
        return empregadofixo;
    }

    public void setEmpregadofixo(Empregadofixo empregadofixo) {
        this.empregadofixo = empregadofixo;
    }
   
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    public Collection<Empregado> getAlumnos() {
        return alumnos;
    }

    public void setAlumnos(Collection<Empregado> alumnos) {
        this.alumnos = alumnos;
    }
    



    public Curso getCurso() {
        return curso;
    }

    public void setCurso(Curso curso) {
        this.curso = curso;
    }

 
    public void setAlumnos(Set<Empregado> alumnos) {
        this.alumnos = alumnos;
    }




}


