package POJOS;
// Generated 02-feb-2021 0:15:37 by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;

/**
 * Empregadotemporal generated by hbm2java
 */
public class Empregadotemporal  extends Empregado implements Serializable{
 
     private Date dataInicio;
     private Date dataFin;
     private Double costeHora;
     private Double numHoras;

    public Empregadotemporal() {
    }
  
  
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }
    public Date getDataFin() {
        return this.dataFin;
    }
    
    public void setDataFin(Date dataFin) {
        this.dataFin = dataFin;
    }
    public Double getCosteHora() {
        return this.costeHora;
    }
    
    public void setCosteHora(Double costeHora) {
        this.costeHora = costeHora;
    }
    public Double getNumHoras() {
        return this.numHoras;
    }
    
    public void setNumHoras(Double numHoras) {
        this.numHoras = numHoras;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Empregadotemporal other = (Empregadotemporal) obj;
        return true;
    }




}


