package POJOS;
// Generated 02-feb-2021 0:15:37 by Hibernate Tools 3.6.0

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * Empregado generated by hbm2java
 */
public class Empregado implements java.io.Serializable {

    private String nss;
    private Empregado supervisor;
    private Departamento departamento;
    private String nome;
    private String apelido1;
    private String apelido2;
    private Enderezo enderezo;
    private Date dataNacemento;
    private Character sexo;
    private List <Familiar> familiares = new ArrayList();   
    private Map <String,String> telefonos = new HashMap();
    private Set <EmpregadoProxecto> empregadoProxectos = new HashSet();
    private Set <Edicion> ediciones = new HashSet();
    private Set <Empregado> supervisa=new HashSet();
    private Vehiculo vehiculo;
   

    public Empregado() {
    }

    public Empregado(String nss, String nome, String apelido1) {
        this.nss = nss;
        this.nome = nome;
        this.apelido1 = apelido1;
    }

    public Empregado(String nss) {
        this.nss = nss;
    }

   
    

    public String getNss() {
        return this.nss;
    }

    public void setNss(String nss) {
        this.nss = nss;
    }

    public Empregado getSupervisor() {
        return this.supervisor;
    }

    public void setSupervisor(Empregado supervisor) {
        this.supervisor = supervisor;
    }

    public Departamento getDepartamento() {
        return this.departamento;
    }

    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getApelido1() {
        return this.apelido1;
    }

    public void setApelido1(String apelido1) {
        this.apelido1 = apelido1;
    }

    public String getApelido2() {
        return this.apelido2;
    }

    public void setApelido2(String apelido2) {
        this.apelido2 = apelido2;
    }

    public Enderezo getEnderezo() {
        return enderezo;
    }

    public void setEnderezo(Enderezo enderezo) {
        this.enderezo = enderezo;
    }

    public Date getDataNacemento() {
        return this.dataNacemento;
    }

    public void setDataNacemento(Date dataNacemento) {
        this.dataNacemento = dataNacemento;
    }

    public Character getSexo() {
        return this.sexo;
    }

    public void setSexo(Character sexo) {
        this.sexo = sexo;
    }

    public List<Familiar> getFamiliares() {
        return familiares;
    }

    public void setFamiliares(List<Familiar> familiares) {
        this.familiares = familiares;
    }

    public Map<String, String> getTelefonos() {
        return telefonos;
    }

    public void setTelefonos(Map<String, String> telefonos) {
        this.telefonos = telefonos;
    }

    public Set<EmpregadoProxecto> getEmpregadoProxectos() {
        return empregadoProxectos;
    }

    public void setEmpregadoProxectos(Set<EmpregadoProxecto> empregadoProxectos) {
        this.empregadoProxectos = empregadoProxectos;
    }

    public Set<Edicion> getEdiciones() {
        return ediciones;
    }

    public void setEdiciones(Set<Edicion> ediciones) {
        this.ediciones = ediciones;
    }

    public Set<Empregado> getSupervisa() {
        return supervisa;
    }

    public void setSupervisa(Set<Empregado> supervisa) {
        this.supervisa = supervisa;
    }

  
 
  
 

    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }

    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    
     @Override
    public String toString() {
        return "Empregado{" + "nss=" + nss + ", nome=" + nome + ", sexo=" + sexo + ", enderezo=" + enderezo + '}';
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + Objects.hashCode(this.nss);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
          if (obj instanceof Empregadotemporal) {
        } else {
              return false;
        }
            if (obj instanceof Empregadofixo) {
        } else {
              return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Empregado other = (Empregado) obj;
        return Objects.equals(this.nss, other.nss);
    }

   

}
