package POJOS;
// Generated 02-feb-2021 0:15:37 by Hibernate Tools 3.6.0

import java.util.Objects;




/**
 * EmpregadoProxectoId generated by hbm2java
 */
public class EmpregadoProxectoId  implements java.io.Serializable {


     private String nssempregado;
     private int numProxecto;

    public EmpregadoProxectoId() {
    }

    public EmpregadoProxectoId(String nssempregado, int numProxecto) {
       this.nssempregado = nssempregado;
       this.numProxecto = numProxecto;
    }
   
    public String getNssempregado() {
        return this.nssempregado;
    }
    
    public void setNssempregado(String nssempregado) {
        this.nssempregado = nssempregado;
    }
    public int getNumProxecto() {
        return this.numProxecto;
    }
    
    public void setNumProxecto(int numProxecto) {
        this.numProxecto = numProxecto;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.nssempregado);
        hash = 97 * hash + this.numProxecto;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final EmpregadoProxectoId other = (EmpregadoProxectoId) obj;
        if (!Objects.equals(this.nssempregado, other.nssempregado)) {
            return false;
        }
        if (this.numProxecto != other.numProxecto) {
            return false;
        }
        return true;
    }



}


