package POJOS;
// Generated 02-feb-2021 0:15:37 by Hibernate Tools 3.6.0


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.SortedMap;
import java.util.TreeMap;

/**
 * Empregadofixo generated by hbm2java
 */
public class Empregadofixo  extends Empregado implements Serializable {

     private Double salario;
     private Date dataAlta;
     private String categoria;
     private SortedMap <Date,Double> horasextras = new TreeMap();
     private Set <Edicion> edicionprofesor = new HashSet();
     private Set <Departamento> deptodirector = new HashSet(0);

    public Empregadofixo() {
    }

    public Empregadofixo(String nss) {
        super(nss);
    }

   
    public Empregadofixo(Double salario, Date dataAlta, String categoria, String nss, String nome, String apelido1) {
        super(nss, nome, apelido1);
        this.salario = salario;
        this.dataAlta = dataAlta;
        this.categoria = categoria;
    }

    public Empregadofixo(Double salario, Date dataAlta, String categoria) {
        this.salario = salario;
        this.dataAlta = dataAlta;
        this.categoria = categoria;
    }

    public Double getSalario() {
        return salario;
    }

    public void setSalario(Double salario) {
        this.salario = salario;
    }

    public Date getDataAlta() {
        return dataAlta;
    }

    public void setDataAlta(Date dataAlta) {
        this.dataAlta = dataAlta;
    }

    public String getCategoria() {
        return categoria;
    }

    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    public SortedMap<Date, Double> getHorasextras() {
        return horasextras;
    }

    public void setHorasextras(SortedMap<Date, Double> horasextras) {
        this.horasextras = horasextras;
    }

    public Set<Edicion> getEdicionprofesor() {
        return edicionprofesor;
    }

    public void setEdicionprofesor(Set<Edicion> edicionprofesor) {
        this.edicionprofesor = edicionprofesor;
    }

  

 

    public Set<Departamento> getDeptodirector() {
        return deptodirector;
    }

    public void setDeptodirector(Set<Departamento> deptodirector) {
        this.deptodirector = deptodirector;
    }

  


}


