package POJOS;
// Generated 02-feb-2021 0:15:37 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.Objects;

/**
 * Familiar generated by hbm2java
 */
public class Familiar  implements java.io.Serializable {
     private String nss;
     private String nome;
     private String apelido1;
     private String apelido2;
     private Date dataNacimento;
     private String parentesco;
     private char sexo;

    public Familiar() {
    }

    public Familiar(String NSS, String nome, String apelido1, String apelido2, Date dataNacimento, String parentesco, char sexo) {
        this.nss = NSS;
        this.nome = nome;
        this.apelido1 = apelido1;
        this.apelido2 = apelido2;
        this.dataNacimento = dataNacimento;
        this.parentesco = parentesco;
        this.sexo = sexo;
    }

    public String getNss() {
        return nss;
    }

    public void setNss(String nss) {
        this.nss = nss;
    }

  

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getApelido1() {
        return apelido1;
    }

    public void setApelido1(String apelido1) {
        this.apelido1 = apelido1;
    }

    public String getApelido2() {
        return apelido2;
    }

    public void setApelido2(String apelido2) {
        this.apelido2 = apelido2;
    }

    public Date getDataNacimento() {
        return dataNacimento;
    }

    public void setDataNacimento(Date dataNacimento) {
        this.dataNacimento = dataNacimento;
    }

    public String getParentesco() {
        return parentesco;
    }

    public void setParentesco(String parentesco) {
        this.parentesco = parentesco;
    }

    public char getSexo() {
        return sexo;
    }

    public void setSexo(char sexo) {
        this.sexo = sexo;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 47 * hash + Objects.hashCode(this.nss);
        hash = 47 * hash + Objects.hashCode(this.nome);
        hash = 47 * hash + Objects.hashCode(this.apelido1);
        hash = 47 * hash + Objects.hashCode(this.apelido2);
        hash = 47 * hash + Objects.hashCode(this.dataNacimento);
        hash = 47 * hash + Objects.hashCode(this.parentesco);
        hash = 47 * hash + this.sexo;
        return hash;
    }

   

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Familiar other = (Familiar) obj;
        return Objects.equals(this.nss, other.nss);
    }
    

	
   


}


