package POJOS;
// Generated 02-feb-2021 0:15:37 by Hibernate Tools 3.6.0


import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

/**
 * Proxecto generated by hbm2java
 */
public class Proxecto  implements java.io.Serializable {


     private int numProxecto;
     private Departamento departamento;
     private String nomeProxecto;
     private String lugar;
     private Collection <EmpregadoProxecto> empregadoProxectos = new ArrayList();

    public Proxecto() {
    }

    public Proxecto(int numProxecto) {
        this.numProxecto = numProxecto;
    }

	
    public Proxecto(int numProxecto, Departamento departamento, String nomeProxecto, String lugar) {
        this.numProxecto = numProxecto;
        this.departamento = departamento;
        this.nomeProxecto = nomeProxecto;
        this.lugar = lugar;
    }
    public Proxecto(int numProxecto, Departamento departamento, String nomeProxecto, String lugar, Set empregadoProxectos) {
       this.numProxecto = numProxecto;
       this.departamento = departamento;
       this.nomeProxecto = nomeProxecto;
       this.lugar = lugar;
       this.empregadoProxectos = empregadoProxectos;
    }
   
    public int getNumProxecto() {
        return this.numProxecto;
    }
    
    public void setNumProxecto(int numProxecto) {
        this.numProxecto = numProxecto;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNomeProxecto() {
        return this.nomeProxecto;
    }
    
    public void setNomeProxecto(String nomeProxecto) {
        this.nomeProxecto = nomeProxecto;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    public Collection<EmpregadoProxecto> getEmpregadoProxectos() {
        return empregadoProxectos;
    }

    public void setEmpregadoProxectos(Collection<EmpregadoProxecto> empregadoProxectos) {
        this.empregadoProxectos = empregadoProxectos;
    }
   
    
    
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + this.numProxecto;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Proxecto other = (Proxecto) obj;
        if (this.numProxecto != other.numProxecto) {
            return false;
        }
        return true;
    }




}


