package pojos;
// Generated 23 ene. 2025 9:18:23 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Collection;

/**
 * Departamento generated by hbm2java
 */
public class Departamento implements java.io.Serializable {

    private int numDepartamento;
    private String nomeDepartamento;

    public Departamento() {}

    public Departamento(String nomeDepartamento) {
        this.nomeDepartamento = nomeDepartamento;
    }

    public int getNumDepartamento() {
        return this.numDepartamento;
    }

    public void setNumDepartamento(int numDepartamento) {
        this.numDepartamento = numDepartamento;
    }

    public String getNomeDepartamento() {
        return this.nomeDepartamento;
    }

    public void setNomeDepartamento(String nomeDepartamento) {
        this.nomeDepartamento = nomeDepartamento;
    }

    @Override public String toString() {
        return "Departamento{" +
                "numDepartamento=" + numDepartamento +
                ", nomeDepartamento='" + nomeDepartamento + '\'' +
                '}';
    }

    /* OTROS MAPEOS */
    // Mapeo de los lugares como ibag de componentes
    private Collection<String> lugares = new ArrayList<>();
    public Collection<String> getLugares() {
        return lugares;
    }
    public void setLugares(Collection<String> lugares) {
        this.lugares = lugares;
    }

    // Mapeo del Director
    private Empregado director;
    public Empregado getDirector() {
        return director;
    }
    public void setDirector(Empregado director) {
        this.director = director;
    }

    // Mapeo de los proxectos que controla
    private Collection<Proxecto> proxectosControlados = new ArrayList<>();
    public Collection<Proxecto> getProxectosControlados() {
        return proxectosControlados;
    }
    public void setProxectosControlados(Collection<Proxecto> proxectosControlados) {
        this.proxectosControlados = proxectosControlados;
    }
}
