package pojos;
// Generated 23 ene. 2025 9:18:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Proxecto generated by hbm2java
 */
public class Proxecto implements java.io.Serializable {

    private int numProxecto;
    private String nomeProxecto;
    private String lugar;

    public Proxecto() {
    }

    public Proxecto(int numProxecto, String nomeProxecto, String lugar) {
        this.numProxecto = numProxecto;
        this.nomeProxecto = nomeProxecto;
        this.lugar = lugar;
    }

    public int getNumProxecto() {
        return this.numProxecto;
    }

    public void setNumProxecto(int numProxecto) {
        this.numProxecto = numProxecto;
    }

    public String getNomeProxecto() {
        return this.nomeProxecto;
    }

    public void setNomeProxecto(String nomeProxecto) {
        this.nomeProxecto = nomeProxecto;
    }

    public String getLugar() {
        return this.lugar;
    }

    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    @Override public String toString() {
        return "Proxecto{" +
                "numProxecto=" + numProxecto +
                ", nomeProxecto='" + nomeProxecto + '\'' +
                ", lugar='" + lugar + '\'' +
                ", departamentoControla=" + departamentoControla +
                '}';
    }

    // region Mapeo del departamento
    private Departamento departamentoControla;
    public Departamento getDepartamentoControla() {
        return departamentoControla;
    }
    public void setDepartamentoControla(Departamento departamentoControla) {
        this.departamentoControla = departamentoControla;
    }
    // endregion

    // region EMPLEADOS QUE PARTICIPAN EN EL PROXECTO
    private Set<Empregado> participantes = new HashSet<>();
    public Set<Empregado> getParticipantes() {
        return participantes;
    }
    public void setParticipantes(Set<Empregado> participantes) {
        this.participantes = participantes;
    }
    // endregion
}