package pojos;
// Generated 23 ene. 2025 9:06:45 by Hibernate Tools 4.3.1

import javax.persistence.*;

import org.hibernate.annotations.CollectionId;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Type;

import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "DEPARTAMENTO",
        schema = "dbo",
        catalog = "EmpresaHB",
        uniqueConstraints = @UniqueConstraint(columnNames = "Nome_departamento")
)
public class Departamento implements java.io.Serializable {
    @Id @GeneratedValue(generator = "increment")
    @GenericGenerator(name = "increment", strategy = "increment")
    @Column(name = "Num_departamento", unique = true, nullable = false)
    private int numDepartamento;

    @Column(name = "Nome_departamento", unique = true, nullable = false, length = 25)
    private String nomeDepartamento;

    /* Mapeo de los lugares */
    @ElementCollection @CollectionTable(name = "LUGAR", joinColumns = @JoinColumn(name = "Num_departamento"))
    @Column(name = "lugar", length = 15, nullable = false) @GenericGenerator(name ="increment", strategy = "increment")
    @CollectionId(columns = @Column(name = "id"), generator = "increment", type = @Type(type = "int"))
    Collection<String> lugares = new ArrayList<>();

    public Collection<String> getLugares() {
        return lugares;
    }

    public void setLugares(Collection<String> lugares) {
        this.lugares = lugares;
    }

    /* Mapeo de los proxectos */
    @OneToMany(mappedBy = "numDepartControla", fetch = FetchType.LAZY)
    private Set<Proxecto> proxectos = new LinkedHashSet<>();

    public Set<Proxecto> getProxectos() {
        return proxectos;
    }
    public void setProxectos(Set<Proxecto> proxectos) {
        this.proxectos = proxectos;
    }

    // OBJETO BASE
    public Departamento() {
    }

    public Departamento(String nomeDepartamento) {
        this.nomeDepartamento = nomeDepartamento;
    }

    public Departamento(int numDepartamento, String nomeDepartamento) {
        this.numDepartamento = numDepartamento;
        this.nomeDepartamento = nomeDepartamento;
    }

    public int getNumDepartamento() {
        return this.numDepartamento;
    }
    public void setNumDepartamento(int numDepartamento) {
        this.numDepartamento = numDepartamento;
    }

    public String getNomeDepartamento() {
        return this.nomeDepartamento;
    }
    public void setNomeDepartamento(String nomeDepartamento) {
        this.nomeDepartamento = nomeDepartamento;
    }

    @Override
    public String toString() {
        return "Departamento{" + "numDepartamento=" + numDepartamento + ", nomeDepartamento=" + nomeDepartamento + '}';
    }
}
