package pojos;
// Generated 23 ene. 2025 9:06:45 by Hibernate Tools 4.3.1

import javax.persistence.*;
import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Proxecto generated by hbm2java
 */
@Entity
@Table(name = "PROXECTO",
        schema = "dbo",
        catalog = "EmpresaHB",
        uniqueConstraints = @UniqueConstraint(columnNames = "Nome_proxecto")
)
public class Proxecto implements java.io.Serializable {
    @Id @Column(name = "Num_proxecto", unique = true, nullable = false)
    private int numProxecto;
    @Column(name = "Nome_proxecto", unique = true, nullable = false, length = 25)
    private String nomeProxecto;
    @Column(name = "Lugar", nullable = false, length = 25)
    private String lugar;

    public Proxecto() {
    }

    public Proxecto(int numProxecto, String nomeProxecto, String lugar) {
        this.numProxecto = numProxecto;
        this.nomeProxecto = nomeProxecto;
        this.lugar = lugar;
    }

    public int getNumProxecto() {
        return this.numProxecto;
    }
    public void setNumProxecto(int numProxecto) {
        this.numProxecto = numProxecto;
    }

    public String getNomeProxecto() {
        return this.nomeProxecto;
    }
    public void setNomeProxecto(String nomeProxecto) {
        this.nomeProxecto = nomeProxecto;
    }

    public String getLugar() {
        return this.lugar;
    }
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    @Override
    public String toString() {
        return "Proxecto{" + "numProxecto=" + numProxecto + ", nomeProxecto=" + nomeProxecto + ", lugar=" + lugar + '}';
    }

    // region EMPREGADO_PROXECTO
    @ManyToMany @JoinTable(name = "EMPREGADO_PROXECTO",
            joinColumns = @JoinColumn(name = "Num_proxecto"),
            inverseJoinColumns = @JoinColumn(name = "NSS_Empregado")
    ) private Set<Empregado> empregados = new LinkedHashSet<>();

    public Set<Empregado> getEmpregados() {
        return empregados;
    }

    public void setEmpregados(Set<Empregado> empregados) {
        this.empregados = empregados;
    }
    // endregion

    // region DEPARTAMENTO
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "Num_depart_controla", nullable = false)
    private Departamento numDepartControla;

    public Departamento getNumDepartControla() {
        return numDepartControla;
    }
    public void setNumDepartControla(Departamento numDepartControla) {
        this.numDepartControla = numDepartControla;
    }
    // endregion
}
