name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts for ${{ matrix.os }}
        uses: actions/download-artifact@v4
        with:
          name: db-sniffer-${{ matrix.os }}
          path: ./downloads

      - name: Create GitHub Release
        uses: gh-actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: 'This is a release created from the artifacts uploaded by the Build workflow.'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
